/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISafeswapRouter } from "./ISafeswapRouter";
export type { SafeswapPair } from "./SafeswapPair";
