/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISafeswapFactory,
  ISafeswapFactoryInterface,
} from "../../../contracts/FeeJar.sol/ISafeswapFactory";

const _abi = [
  {
    inputs: [],
    name: "feeTo",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ISafeswapFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ISafeswapFactoryInterface {
    return new utils.Interface(_abi) as ISafeswapFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISafeswapFactory {
    return new Contract(address, _abi, signerOrProvider) as ISafeswapFactory;
  }
}
