/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { ISafeswapCallee } from "./ISafeswapCallee";
export type { ISafeswapERC20 } from "./ISafeswapERC20";
export type { ISafeswapFactory } from "./ISafeswapFactory";
export type { ISafeswapPair } from "./ISafeswapPair";
