/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as safemoonLibSol from "./SafemoonLib.sol";
export { Safemoon__factory } from "./Safemoon__factory";
