/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Greater__factory } from "./Greater__factory";
export { NewGreater__factory } from "./NewGreater__factory";
