/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as safeswapPairSol from "./SafeswapPair.sol";
export * as interfaces from "./interfaces";
export * as libraries from "./libraries";
export { SafeswapERC20__factory } from "./SafeswapERC20__factory";
export { SafeswapFactory__factory } from "./SafeswapFactory__factory";
