/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as safemoonLibSol from "./SafemoonLib.sol";
export type { safemoonLibSol };
export type { Safemoon } from "./Safemoon";
