/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as safeswapPairSol from "./SafeswapPair.sol";
export type { safeswapPairSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as libraries from "./libraries";
export type { libraries };
export type { SafeswapERC20 } from "./SafeswapERC20";
export type { SafeswapFactory } from "./SafeswapFactory";
