/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { ISafeswapFactory } from "./ISafeswapFactory";
export type { ISafeswapPair } from "./ISafeswapPair";
export type { ISafeswapRouter01 } from "./ISafeswapRouter01";
export type { ISafeswapRouter02 } from "./ISafeswapRouter02";
export type { IWETH } from "./IWETH";
