/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as libSol from "./lib.sol";
export type { libSol };
export type { LibDiamond } from "./LibDiamond";
export type { RouterStorageLib } from "./RouterStorageLib";
