/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as factorySol from "./Factory.sol";
export type { factorySol };
import type * as greaterSol from "./Greater.sol";
export type { greaterSol };
