/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1967Proxy } from "./ERC1967Proxy";
export type { ERC1967Upgrade } from "./ERC1967Upgrade";
export type { IBeacon } from "./IBeacon";
export type { IERC1822Proxiable } from "./IERC1822Proxiable";
export type { OptimizedTransparentUpgradeableProxy } from "./OptimizedTransparentUpgradeableProxy";
export type { Proxy } from "./Proxy";
