/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFeeJar,
  IFeeJarInterface,
} from "../../../contracts/interfaces/IFeeJar";

const _abi = [
  {
    inputs: [],
    name: "fee",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IFeeJar__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeJarInterface {
    return new utils.Interface(_abi) as IFeeJarInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFeeJar {
    return new Contract(address, _abi, signerOrProvider) as IFeeJar;
  }
}
