/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISafeswapMigrator,
  ISafeswapMigratorInterface,
} from "../../../contracts/interfaces/ISafeswapMigrator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountTokenMin",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountETHMin",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
    ],
    name: "migrate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISafeswapMigrator__factory {
  static readonly abi = _abi;
  static createInterface(): ISafeswapMigratorInterface {
    return new utils.Interface(_abi) as ISafeswapMigratorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISafeswapMigrator {
    return new Contract(address, _abi, signerOrProvider) as ISafeswapMigrator;
  }
}
