/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as optimizeProxy from "./OptimizeProxy";
export type { optimizeProxy };
import type * as proxyAdmin from "./ProxyAdmin";
export type { proxyAdmin };
